#!/usr/bin/env bash
#### AUTORUN ####
xsetroot -solid \#303030
xsetroot -cursor_name left_ptr

if [ $1 == 0 ]; then
    sxhkd &
    polybar main &
    kitty -- fish -c upgrade &
else
    pkill -USR1 -x sxhkd
fi

#### MONITORS ####
bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 10

#### BSPWM configuration ####
bspc config border_width               2
bspc config window_gap                 6
bspc config top_padding                24
bspc config bottom_padding             0
bspc config left_padding               0
bspc config right_padding              0
bspc config single_monocle             true
bspc config click_to_focus             any
bspc config honor_size_hints           true
bspc config pointer_follows_focus      false
bspc config pointer_follows_monitor    true
bspc config split_ratio                0.60
bspc config borderless_monocle         false
bspc config gapless_monocle            false
bspc config focus_follows_pointer      false
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier           mod4
bspc config pointer_action1            move
bspc config pointer_action2            resize_side
bspc config pointer_action3            resize_corner

#### BSPWM coloring ####
bspc config normal_border_color   "#555555"
bspc config active_border_color   "#555555"
bspc config focused_border_color  "#bbbbbb"
bspc config presel_feedback_color "#303030"

#### BSPWM rules ####
bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a float state=floating
bspc rule -a org-igoweb-cgoban-CGoban state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Emacs:*:seledit state=floating
bspc rule -a Safeeyes state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Anki state=pseudo_tiled
