#! /bin/sh
#### AUTORUN ####
xsetroot -solid \#303030
[ $1 == 0 ] && sxhkd &
[ $1 == 0 ] && polybar top &
[ $1 == 0 ] && upgrade &

#### MONITORS ####
bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 10

#### BSPWM configuration ####
bspc config border_radius              0
bspc config border_width               2
bspc config window_gap                 6
bspc config top_padding                24
bspc config bottom_padding             0
bspc config left_padding               0
bspc config right_padding              0
bspc config single_monocle             true
bspc config click_to_focus             any
bspc config shallow_first_click        true
bspc config honor_size_hints           true
bspc config pointer_follows_focus      false
bspc config pointer_follows_monitor    true
bspc config split_ratio                0.60
bspc config borderless_monocle         false
bspc config gapless_monocle            false
bspc config focus_by_distance          true
bspc config focus_follows_pointer      true
bspc config history_aware_focus        true
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier           mod4
bspc config pointer_action1            move
bspc config pointer_action2            resize_side
bspc config pointer_action3            resize_corner

#### BSPWM coloring ####
bspc config normal_border_color   "#888888"
bspc config active_border_color   "#888888"
bspc config urgent_border_color   "#888888"
bspc config focused_border_color  "#bbc5ff"
bspc config presel_feedback_color "#303030"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a float state=floating
bspc rule -a org-igoweb-cgoban-CGoban state=floating
