# Configuration documentation is available at https://dystroy.org/broot

[[verbs]]
invocation = "edit"
shortcut = "e"
execution = "nvim {file}"

[[verbs]]
invocation = "zathura"
shortcut = "z"
execution = "zathura {file}"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "create {subpath}"
shortcut = "a"
execution = "$EDITOR {directory}/{subpath}"

[[verbs]]
invocation = "view"
shortcut = "v"
execution = "$PAGER {file}"
