# Configuration documentation is available at https://dystroy.org/broot

[[verbs]]
invocation = "edit"
key = "F2"
shortcut = "e"
execution = "nvim {file} '+cd {directory}'"
from_shell = true

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"

[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"
